version: '2'
services:
  disconf_zk:
    container_name: disconf_zk
    image: 192.168.6.185/zrar/css-zk
    restart: always
    ports:
      - 2181:2181
    networks:
      - core
  redis:
    container_name: disconf_redis
    image: 192.168.6.185/zrar/redis:5.0.3
    restart: always
    command: redis-server --appendonly yes --requirepass "123456"
    volumes:
      - ./data/redis:/data
    networks:
      - core
  mysql:
    container_name: disconf_mysql
    image: 192.168.6.185/zrar/mysql:5.7.25
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=123456
       - MYSQL_USER=green
       - MYSQL_PASSWORD=123456
       - MYSQL_DATABASE=disconf
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./data/mysql/:/var/lib/mysql
    networks:
      - core
  nginx:
    container_name: disconf_nginx
    image: 192.168.6.185/zrar/nginx:1.15.8
    restart: always
    ports:
      - 8081:80
    depends_on:
      - disconf_web
    volumes:
      - ./web/war/html:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - core
  disconf_web:
    container_name: disconf_web
    image: 192.168.6.185/zrar/tomcat:8.5.37-jre8-alpine
    restart: always
    depends_on:
      - disconf_zk
      - redis
      - mysql
    volumes:
      - ./web/war:/usr/local/tomcat/webapps/ROOT
    networks:
      - core
networks:
  core:
    driver: bridge
