version: '3.7'
services:
  redis:
    image: 192.168.6.185/zrar/redis:5.0.3
    command: redis-server --appendonly yes --requirepass "123456"
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.app == true]
    networks:
      - kshare_product
networks:
  kshare_product:
    external:
      name: kshare_product