version: '3.7'
services:
  cassandra:
    image: 192.168.6.185/zrar/cassandra:3.11.3
    environment:
     - JVM_OPTS=-Xmx512m -Xms512m
    entrypoint:
     - "sh"
     - "-c"
     - export CASSANDRA_SEEDS=$$(nrOfTasks=`getent hosts tasks.cassandra | wc -l` ; many=`getent hosts tasks.cassandra | awk '{print $$1}' | sed "/$$(hostname --ip-address)/d" | paste -d, -s -` ; printf '%s' $$( [ $${nrOfTasks} -gt 1 ] && echo $${many} || echo "$$(hostname --ip-address)" )) ; /docker-entrypoint.sh cassandra -f
    volumes:
        - cassandraVol:/var/lib/cassandra
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.db == true]
    networks:
     - kshare_product

volumes:
  cassandraVol:
      name: 'cassandra-data-{{.Task.Slot}}'
      driver: rexray/rbd

networks:
  kshare_product:
    external:
      name: kshare_product