version: '3.7'
services:
  aross:
    image: 192.168.6.185/zrar/aross:1.0.5
    restart: always
    environment:
      - "JAVA_OPTS=-Ddisconf.conf_server_host=192.168.6.185:8081 -Ddisconf.app=arkshare_oss -Ddisconf.env=online -Ddisconf.version=1.0"
    extra_hosts:
      - "ShanghaiKShare190:172.16.30.190"
    ports:
      - 8082:8080
    networks:
      - kshare_product

networks:
  kshare_product :
    external:
      name: kshare_product