version: '2'
services:
  redis:
    container_name: redis
    image: 192.168.6.185/zrar/redis:5.0.3
    command: redis-server --appendonly yes --requirepass "123456"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      - kshare
networks:
  kshare: